import type { Metadata } from 'next';
import CopyGuard from './CopyGuard';
import './globals.css';
import './hero.css';
import './hero-motion.css';
import './service-showcase.css';
import './case-studies.css';
import './systems.css';
import './editorial.css';
import './team.css';
import './sections.css';
import './work-gallery.css';
import './works-marquee.css';
import './social-work-gallery.css';
import './curved-ticker.css';
import './testimonials.css';
import './pricing.css';
import './contact-section.css';
import './button-motion.css';
import './content-refresh.css';
import './client-feedback.css';
import './service-showcase-glass.css';
import './studio-pages.css'; // Shared project, pricing and enquiry experiences.
import './navigation.css';
import './project-labels.css';
import './services-refresh.css';
import './contact-refresh.css';
import './legal-pages.css';
import './legal-hero-variants.css';
export const metadata: Metadata = { title:'WEBSTELL | Website Design & Development Agency', description:'Websites that look exceptional and work for you. WEBSTELL creates websites, ecommerce experiences, brand identities and digital products.', icons:{icon:'/assets/brand/webstell-retro-mac.png'} };
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="en"><body><CopyGuard />{children}</body></html>}
